version: '3.8'

services:
  db:
    image: postgres:11.10
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  nats-server:
    image: nats-streaming
    container_name: nats-streaming
    restart: always
    command: -msu 0
    ports:
    - 4222:4222
    - 8222:8222
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    command: redis-server --requirepass redis
    volumes:
      - $PWD/redis-data:/var/lib/redis
    environment:
      - REDIS_REPLICATION_MODE=master
    ports:
    - 6379:6379
  cassandra:
    image: cassandra:3.11
    ports:
      - "9042:9042"
    volumes:
      - ./data/cassandra:/var/lib/cassandra  # Link volume to local data directory to prevent data loss
  statsd:
     image: hopsoft/graphite-statsd
     ports:
       - "8188:80"
       - "2003:2003"
       - "8125:8125"
       - "8126:8126"
  cadence:
     image: ubercadence/server:master-auto-setup  # Update this version number if there are new versions release
     ports:
       - "7933:7933"
       - "7934:7934"
       - "7935:7935"
       - "7939:7939"
     environment:
       - "CASSANDRA_SEEDS=cassandra"
       - "STATSD_ENDPOINT=statsd:8125"
       - "DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml"
     depends_on:
       - cassandra
       - statsd
  cadence-web:
     image: ubercadence/web:3.4.1
     environment:
       - "CADENCE_TCHANNEL_PEERS=cadence:7933"
     ports:
       - "8088:8088"
     depends_on:
       - cadence
volumes:
  db-data:
#  nats-main:
#    image: nats
#    container_name: nats
#    ports:
#    - 4222:4222
#    - 6222:6222
#    - 8222:8222
